[features]
seeds = false
[programs.localnet]
elfo_protocol = "BJgusPC7xJRCGsFcwEwMGExkqdbYRGy3pugoKwkFDzZx"

[programs.devnet]
elfo_protocol = "BJgusPC7xJRCGsFcwEwMGExkqdbYRGy3pugoKwkFDzZx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kristiyandilov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
